### ISSUE TITLE
got stuck after following chapter one

### ISSUE THREAD

**Issue by weykon** [cnwzhjs/blog-uefi-os#3]
I followed Chapter 1, but was prompted in Chapter 2’s println! that there is no such macro definition. Can I add the println! macro separately?
![image](https://github.com/cnwzhjs/blog-uefi-os/assets/36456814/0754ad3e-09d0-4d8d-b3bd-3c4d4b2ce964)

**Comment by cnwzhjs** [comment]
This `println!` is actually from the crate `uefi_services`. Please check if you:

1. add `uefi_services` as your dependency and initialize at startup
2. change edition to '2021' in your `Cargo.toml` or `extern crate uefi_services; use uefi_services::println`

**Comment by weykon** [comment]
yes, and the name is `uefi-services` not `uefi_services`.

**Comment by weykon** [comment]
and where `Boot` type come from ? the SystemTable I import from r_efi, there no generic need.

**Comment by cnwzhjs** [comment]
You may referred to the previous edition of my blog. I updated to the `uefi` and `uefi-services` instead of `r_efi`.
Please checkout the newer version of my blog.
Thanks
